name: NPM Publish
on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Change version
        run: |
          jq '.version = "${{ github.ref_name }}"' package.json > package.new.json
          cp package.new.json package.json
          rm package.new.json

      - run: pnpm install

      - run: pnpm run publish-to-npm

      - run: cd dist && npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
