name: NPM Publish
on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install

      - name: Change version
        run: |
          jq '.version = "${{ github.ref_name }}"' package.json > package.new.json
          cp package.new.json package.json
          rm package.new.json

      - run: bun run publish-to-npm

      - run: cd dist && npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
